version: '3.3'

services:
  db:
    container_name: task_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - development

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - development

  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - development

networks:
  development:
    driver: bridge